import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from "react";

export default function Home() {
  const [name, setName] = React.useState("");
  const [DNI, setDNI] = React.useState("");
  const [data, setData] = React.useState([
      {
        name: "Loading...",
        dni: "-",
      }
    ]);
  const [reload, setReload] = React.useState(0);
  React.useEffect(()=>{
    fetch("/api/entries")
      .then(response => response.json())
      .then(data => {
        setData(data);
      })
  }, [reload])
  const storeContacts = () => {
    fetch("/api/add-entry", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        name: name,
        dni: DNI
      })
    })
      .then(response => response.json())
      .then(data => {
        console.log(data);
        setReload(reload + 1);
      })
  }

  return (
    <React.Fragment className={styles.container}>
      <Head>
        <title>Formulario</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="main">
        <h1>Formulario con Firebase y Next.js</h1>
        <section className="form">
          <label>Nombre:</label>
          <input type="text"  className="form__input" value={name} onChange={e => setName(e.target.value)}/>
          <label>DNI:</label>
          <input type="text" className="form__input" value={DNI} onChange={e => setDNI(e.target.value)}/>
          <button onClick={
            () => {
              storeContacts();
            }
          }>Enviar</button>
        </section>
        <p>Ultimos envíos:</p>
        <section>
          <table>
            <thead>
              <tr>
                <th>Nombre</th>
                <th>DNI</th>
              </tr>
            </thead>
            <tbody>
              {
                data.map(el => {
                  return (<tr key={el.dni}><td>{el.name}</td><td>{el.dni}</td></tr>)
                })
              }
            </tbody>
          </table>
        </section>
      </section>
    </React.Fragment>
  )
}
